// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductCatalog.Infrastructure.Data;

#nullable disable

namespace ProductCatalog.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductCatalog.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CH_Product_Price", "Price >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Teclado Mecânico",
                            Price = 299.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mouse Sem Fio",
                            Price = 89.50m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 3,
                            Name = "Monitor Ultrawide",
                            Price = 1899.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            Name = "Headset Gamer",
                            Price = 199.90m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 5,
                            Name = "Webcam HD",
                            Price = 120.00m,
                            Stock = 35
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
